#set_property -dict {PACKAGE_PIN A9}  [get_ports clk_buf_tp_n]
#set_property -dict {PACKAGE_PIN A10}  [get_ports clk_buf_tp_p]
set_property  -dict {PACKAGE_PIN L39 IOSTANDARD LVCMOS18}  [get_ports dev_clk_out]
set_property  -dict {PACKAGE_PIN Y30 IOSTANDARD LVDS}      [get_ports dev_mcs_fpga_in_n]
set_property  -dict {PACKAGE_PIN Y29 IOSTANDARD LVDS}      [get_ports dev_mcs_fpga_in_p]

set_property  -dict {PACKAGE_PIN N40 IOSTANDARD LVCMOS18}  [get_ports dgpio_0]
set_property  -dict {PACKAGE_PIN G39 IOSTANDARD LVCMOS18}  [get_ports dgpio_1]
set_property  -dict {PACKAGE_PIN N39 IOSTANDARD LVCMOS18}  [get_ports dgpio_2]
set_property  -dict {PACKAGE_PIN H39 IOSTANDARD LVCMOS18}  [get_ports dgpio_3]
set_property  -dict {PACKAGE_PIN P42 IOSTANDARD LVCMOS18}  [get_ports dgpio_4]
set_property  -dict {PACKAGE_PIN H41 IOSTANDARD LVCMOS18}  [get_ports dgpio_5]
set_property  -dict {PACKAGE_PIN W31 IOSTANDARD LVCMOS18}  [get_ports dgpio_6]
set_property  -dict {PACKAGE_PIN P30 IOSTANDARD LVCMOS18}  [get_ports dgpio_7]
set_property  -dict {PACKAGE_PIN W30 IOSTANDARD LVCMOS18}  [get_ports dgpio_8]
set_property  -dict {PACKAGE_PIN F41 IOSTANDARD LVCMOS18}  [get_ports dgpio_9]
set_property  -dict {PACKAGE_PIN F40 IOSTANDARD LVCMOS18}  [get_ports dgpio_10]
set_property  -dict {PACKAGE_PIN M39 IOSTANDARD LVCMOS18}  [get_ports dgpio_11]

set_property  -dict {PACKAGE_PIN G42 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports fpga_mcs_in_n]
set_property  -dict {PACKAGE_PIN G41 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports fpga_mcs_in_p]
set_property  -dict {PACKAGE_PIN M31 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports fpga_ref_clk_n]
set_property  -dict {PACKAGE_PIN N30 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports fpga_ref_clk_p]
set_property  -dict {PACKAGE_PIN J42 IOSTANDARD LVCMOS18}             [get_ports gp_int]
set_property  -dict {PACKAGE_PIN L41 IOSTANDARD LVCMOS18}             [get_ports mode]
set_property  -dict {PACKAGE_PIN M41 IOSTANDARD LVCMOS18}             [get_ports reset_trx]

set_property  -dict {PACKAGE_PIN K40 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports rx1_dclk_out_n]
set_property  -dict {PACKAGE_PIN K39 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports rx1_dclk_out_p]
set_property  -dict {PACKAGE_PIN N38 IOSTANDARD LVCMOS18}             [get_ports rx1_enable]
set_property  -dict {PACKAGE_PIN L42 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports rx1_idata_out_n]
set_property  -dict {PACKAGE_PIN M42 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports rx1_idata_out_p]
set_property  -dict {PACKAGE_PIN M38 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports rx1_qdata_out_n]
set_property  -dict {PACKAGE_PIN M37 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports rx1_qdata_out_p]
set_property  -dict {PACKAGE_PIN N41 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports rx1_strobe_out_n]
set_property  -dict {PACKAGE_PIN P41 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports rx1_strobe_out_p]

set_property  -dict {PACKAGE_PIN J41 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports rx2_dclk_out_n]
set_property  -dict {PACKAGE_PIN J40 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports rx2_dclk_out_p]
set_property  -dict {PACKAGE_PIN N31 IOSTANDARD LVCMOS18}             [get_ports rx2_enable]
set_property  -dict {PACKAGE_PIN L37 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports rx2_idata_out_n]
set_property  -dict {PACKAGE_PIN M36 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports rx2_idata_out_p]
set_property  -dict {PACKAGE_PIN P40 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports rx2_qdata_out_n]
set_property  -dict {PACKAGE_PIN R40 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports rx2_qdata_out_p]
set_property  -dict {PACKAGE_PIN K38 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports rx2_strobe_out_n]
set_property  -dict {PACKAGE_PIN K37 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports rx2_strobe_out_p]

set_property  -dict {PACKAGE_PIN L40 IOSTANDARD LVCMOS18}  [get_ports sm_fan_tach]

set_property  -dict {PACKAGE_PIN J31 IOSTANDARD LVCMOS18}  [get_ports spi_clk]
set_property  -dict {PACKAGE_PIN P28 IOSTANDARD LVCMOS18}  [get_ports spi_dio]
set_property  -dict {PACKAGE_PIN N28 IOSTANDARD LVCMOS18}  [get_ports spi_do]
set_property  -dict {PACKAGE_PIN N29 IOSTANDARD LVCMOS18}  [get_ports spi_en]

set_property  -dict {PACKAGE_PIN T31 IOSTANDARD LVDS}                 [get_ports tx1_dclk_in_n]
set_property  -dict {PACKAGE_PIN U31 IOSTANDARD LVDS}                 [get_ports tx1_dclk_in_p]
set_property  -dict {PACKAGE_PIN K32 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports tx1_dclk_out_n]
set_property  -dict {PACKAGE_PIN L31 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports tx1_dclk_out_p]
set_property  -dict {PACKAGE_PIN R42 IOSTANDARD LVCMOS18}             [get_ports tx1_enable]
set_property  -dict {PACKAGE_PIN U29 IOSTANDARD LVDS}                 [get_ports tx1_idata_in_n]
set_property  -dict {PACKAGE_PIN V29 IOSTANDARD LVDS}                 [get_ports tx1_idata_in_p]
set_property  -dict {PACKAGE_PIN V31 IOSTANDARD LVDS}                 [get_ports tx1_qdata_in_n]
set_property  -dict {PACKAGE_PIN V30 IOSTANDARD LVDS}                 [get_ports tx1_qdata_in_p]
set_property  -dict {PACKAGE_PIN M29 IOSTANDARD LVDS}                 [get_ports tx1_strobe_in_n]
set_property  -dict {PACKAGE_PIN M28 IOSTANDARD LVDS}                 [get_ports tx1_strobe_in_p]

set_property  -dict {PACKAGE_PIN K30 IOSTANDARD LVDS}                 [get_ports tx2_dclk_in_n]
set_property  -dict {PACKAGE_PIN K29 IOSTANDARD LVDS}                 [get_ports tx2_dclk_in_p]
set_property  -dict {PACKAGE_PIN L32 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports tx2_dclk_out_n]
set_property  -dict {PACKAGE_PIN M32 IOSTANDARD LVDS DIFF_TERM TRUE}  [get_ports tx2_dclk_out_p]
set_property  -dict {PACKAGE_PIN R28 IOSTANDARD LVCMOS18}             [get_ports tx2_enable]
set_property  -dict {PACKAGE_PIN H30 IOSTANDARD LVDS}                 [get_ports tx2_idata_in_n]
set_property  -dict {PACKAGE_PIN J30 IOSTANDARD LVDS}                 [get_ports tx2_idata_in_p]
set_property  -dict {PACKAGE_PIN P31 IOSTANDARD LVDS}                 [get_ports tx2_qdata_in_n]
set_property  -dict {PACKAGE_PIN R30 IOSTANDARD LVDS}                 [get_ports tx2_qdata_in_p]
set_property  -dict {PACKAGE_PIN T30 IOSTANDARD LVDS}                 [get_ports tx2_strobe_in_n]
set_property  -dict {PACKAGE_PIN T29 IOSTANDARD LVDS}                 [get_ports tx2_strobe_in_p]

set_property  -dict {PACKAGE_PIN H40 IOSTANDARD LVCMOS18}  [get_ports vadj_test_1]
set_property  -dict {PACKAGE_PIN L29 IOSTANDARD LVCMOS18}  [get_ports vadj_test_2]


# clocks

create_clock -name rx1_dclk_out   -period  2.00 [get_ports rx1_dclk_out_p]
create_clock -name rx2_dclk_out   -period  2.00 [get_ports rx2_dclk_out_p]
create_clock -name tx1_dclk_out   -period  2.00 [get_ports tx1_dclk_out_p]
create_clock -name tx2_dclk_out   -period  2.00 [get_ports tx2_dclk_out_p]

