#set_property  -dict {PACKAGE_PIN G7 }  [get_ports clk_buf_tp_n]
#set_property  -dict {PACKAGE_PIN G8 }  [get_ports clk_buf_tp_p]
set_property  -dict {PACKAGE_PIN AA7 IOSTANDARD LVCMOS18}  [get_ports dev_clk_out]
set_property  -dict {PACKAGE_PIN M13 IOSTANDARD LVDS}  [get_ports dev_mcs_fpga_in_n]
set_property  -dict {PACKAGE_PIN N13 IOSTANDARD LVDS}  [get_ports dev_mcs_fpga_in_p]
set_property  -dict {PACKAGE_PIN AC6 IOSTANDARD LVCMOS18}  [get_ports dgpio_0]
set_property  -dict {PACKAGE_PIN AC8 IOSTANDARD LVCMOS18}  [get_ports dgpio_1]
set_property  -dict {PACKAGE_PIN AC7 IOSTANDARD LVCMOS18}  [get_ports dgpio_2]
set_property  -dict {PACKAGE_PIN AB8 IOSTANDARD LVCMOS18}  [get_ports dgpio_3]
set_property  -dict {PACKAGE_PIN W1  IOSTANDARD LVCMOS18}  [get_ports dgpio_4]
set_property  -dict {PACKAGE_PIN AA1 IOSTANDARD LVCMOS18}  [get_ports dgpio_5]
set_property  -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS18}  [get_ports dgpio_6]
set_property  -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS18}  [get_ports dgpio_7]
set_property  -dict {PACKAGE_PIN L13 IOSTANDARD LVCMOS18}  [get_ports dgpio_8]
set_property  -dict {PACKAGE_PIN AB5 IOSTANDARD LVCMOS18}  [get_ports dgpio_9]
set_property  -dict {PACKAGE_PIN AB6 IOSTANDARD LVCMOS18}  [get_ports dgpio_10]
set_property  -dict {PACKAGE_PIN W4  IOSTANDARD LVCMOS18}  [get_ports dgpio_11]
set_property  -dict {PACKAGE_PIN U4  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100}  [get_ports fpga_mcs_in_n]
set_property  -dict {PACKAGE_PIN U5  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100}  [get_ports fpga_mcs_in_p]
set_property  -dict {PACKAGE_PIN R8  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100}  [get_ports fpga_ref_clk_n]
set_property  -dict {PACKAGE_PIN T8  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100}  [get_ports fpga_ref_clk_p]
set_property  -dict {PACKAGE_PIN AC1 IOSTANDARD LVCMOS18}  [get_ports gp_int]
set_property  -dict {PACKAGE_PIN AC3 IOSTANDARD LVCMOS18}  [get_ports mode]
set_property  -dict {PACKAGE_PIN AB3 IOSTANDARD LVCMOS18}  [get_ports reset_trx]
set_property  -dict {PACKAGE_PIN Y3  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100}  [get_ports rx1_dclk_out_n]
set_property  -dict {PACKAGE_PIN Y4  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100}  [get_ports rx1_dclk_out_p]
set_property  -dict {PACKAGE_PIN W5  IOSTANDARD LVCMOS18}  [get_ports rx1_enable]
set_property  -dict {PACKAGE_PIN Y1  IOSTANDARD LVDS  DIFF_TERM_ADV TERM_100}  [get_ports rx1_idata_out_n]
set_property  -dict {PACKAGE_PIN Y2  IOSTANDARD LVDS  DIFF_TERM_ADV TERM_100}  [get_ports rx1_idata_out_p]
set_property  -dict {PACKAGE_PIN V3  IOSTANDARD LVDS  DIFF_TERM_ADV TERM_100}  [get_ports rx1_qdata_out_n]
set_property  -dict {PACKAGE_PIN V4  IOSTANDARD LVDS  DIFF_TERM_ADV TERM_100}  [get_ports rx1_qdata_out_p]
set_property  -dict {PACKAGE_PIN V1  IOSTANDARD LVDS  DIFF_TERM_ADV TERM_100}  [get_ports rx1_strobe_out_n]
set_property  -dict {PACKAGE_PIN V2  IOSTANDARD LVDS  DIFF_TERM_ADV TERM_100}  [get_ports rx1_strobe_out_p]
set_property  -dict {PACKAGE_PIN AC4 IOSTANDARD LVDS  DIFF_TERM_ADV TERM_100}  [get_ports rx2_dclk_out_n]
set_property  -dict {PACKAGE_PIN AB4 IOSTANDARD LVDS  DIFF_TERM_ADV TERM_100}  [get_ports rx2_dclk_out_p]
set_property  -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS18}  [get_ports rx2_enable]
set_property  -dict {PACKAGE_PIN Y9  IOSTANDARD LVDS  DIFF_TERM_ADV TERM_100}  [get_ports rx2_idata_out_n]
set_property  -dict {PACKAGE_PIN Y10 IOSTANDARD LVDS  DIFF_TERM_ADV TERM_100}  [get_ports rx2_idata_out_p]
set_property  -dict {PACKAGE_PIN W6  IOSTANDARD LVDS  DIFF_TERM_ADV TERM_100}  [get_ports rx2_qdata_out_n]
set_property  -dict {PACKAGE_PIN W7  IOSTANDARD LVDS  DIFF_TERM_ADV TERM_100}  [get_ports rx2_qdata_out_p]
set_property  -dict {PACKAGE_PIN AA12 IOSTANDARD LVDS  DIFF_TERM_ADV TERM_100} [get_ports rx2_strobe_out_n]
set_property  -dict {PACKAGE_PIN Y12 IOSTANDARD LVDS  DIFF_TERM_ADV TERM_100}  [get_ports rx2_strobe_out_p]
set_property  -dict {PACKAGE_PIN AA6 IOSTANDARD LVCMOS18}  [get_ports sm_fan_tach]
set_property  -dict {PACKAGE_PIN M10 IOSTANDARD LVCMOS18}  [get_ports spi_clk]
set_property  -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS18}  [get_ports spi_dio]
set_property  -dict {PACKAGE_PIN P12 IOSTANDARD LVCMOS18}  [get_ports spi_do]
set_property  -dict {PACKAGE_PIN N12 IOSTANDARD LVCMOS18}  [get_ports spi_en]
set_property  -dict {PACKAGE_PIN V11 IOSTANDARD LVDS}  [get_ports tx1_dclk_in_n]
set_property  -dict {PACKAGE_PIN V12 IOSTANDARD LVDS}  [get_ports tx1_dclk_in_p]
set_property  -dict {PACKAGE_PIN N11 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100}  [get_ports tx1_dclk_out_n]
set_property  -dict {PACKAGE_PIN P11 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100}  [get_ports tx1_dclk_out_p]
set_property  -dict {PACKAGE_PIN W2  IOSTANDARD LVCMOS18}  [get_ports tx1_enable]
set_property  -dict {PACKAGE_PIN T11 IOSTANDARD LVDS}  [get_ports tx1_idata_in_n]
set_property  -dict {PACKAGE_PIN U11 IOSTANDARD LVDS}  [get_ports tx1_idata_in_p]
set_property  -dict {PACKAGE_PIN U6  IOSTANDARD LVDS}  [get_ports tx1_qdata_in_n]
set_property  -dict {PACKAGE_PIN V6  IOSTANDARD LVDS}  [get_ports tx1_qdata_in_p]
set_property  -dict {PACKAGE_PIN V7  IOSTANDARD LVDS}  [get_ports tx1_strobe_in_n]
set_property  -dict {PACKAGE_PIN V8  IOSTANDARD LVDS}  [get_ports tx1_strobe_in_p]
set_property  -dict {PACKAGE_PIN L11 IOSTANDARD LVDS}  [get_ports tx2_dclk_in_n]
set_property  -dict {PACKAGE_PIN M11 IOSTANDARD LVDS}  [get_ports tx2_dclk_in_p]
set_property  -dict {PACKAGE_PIN N8  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100}  [get_ports tx2_dclk_out_n]
set_property  -dict {PACKAGE_PIN N9  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100}  [get_ports tx2_dclk_out_p]
set_property  -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS18}  [get_ports tx2_enable]
set_property  -dict {PACKAGE_PIN K15 IOSTANDARD LVDS}  [get_ports tx2_idata_in_n]
set_property  -dict {PACKAGE_PIN L15 IOSTANDARD LVDS}  [get_ports tx2_idata_in_p]
set_property  -dict {PACKAGE_PIN K12 IOSTANDARD LVDS}  [get_ports tx2_qdata_in_n]
set_property  -dict {PACKAGE_PIN L12 IOSTANDARD LVDS}  [get_ports tx2_qdata_in_p]
set_property  -dict {PACKAGE_PIN U8  IOSTANDARD LVDS}  [get_ports tx2_strobe_in_n]
set_property  -dict {PACKAGE_PIN U9  IOSTANDARD LVDS}  [get_ports tx2_strobe_in_p]
set_property  -dict {PACKAGE_PIN AA2 IOSTANDARD LVCMOS18}  [get_ports vadj_test_1]
set_property  -dict {PACKAGE_PIN T7  IOSTANDARD LVCMOS18}  [get_ports vadj_test_2]


# clocks

#create_clock -name tx_ref_clk     -period  4.00 [get_ports ref_clk0_p]
#create_clock -name rx_ref_clk     -period  4.00 [get_ports ref_clk1_p]
#create_clock -name tx_div_clk     -period  4.00 [get_pins i_system_wrapper/system_i/util_adrv9009_xcvr/inst/i_xch_0/i_gthe4_channel/TXOUTCLK]
#create_clock -name rx_div_clk     -period  4.00 [get_pins i_system_wrapper/system_i/util_adrv9009_xcvr/inst/i_xch_0/i_gthe4_channel/RXOUTCLK]
#create_clock -name rx_os_div_clk  -period  4.00 [get_pins i_system_wrapper/system_i/util_adrv9009_xcvr/inst/i_xch_2/i_gthe4_channel/RXOUTCLK]
